# Use the latest R version as base image
FROM rocker/tidyverse:4.3

# Install system dependencies for certain R packages
RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev \
    libssl-dev \
    libglpk-dev \
    libgit2-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libudunits2-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install R packages from CRAN
RUN R -e "install.packages(c('igraph', 'devtools','RANN', 'WeightedCluster', 'corpcor', 'weights', 'Hmisc', 'Matrix', 'matrixStats', 'plyr', 'irlba', 'grDevices', 'patchwork', 'gtools', 'ggplot2', 'umap', 'entropy', 'Rtsne', 'dbscan', 'cowplot', 'scales', 'plotfunctions', 'proxy', 'methods', 'rlang', 'Seurat', 'data.table', 'foreach', 'doParallel', 'concaveman', 'parallelDist', 'pbapply', 'pliman', 'tidyr', 'tidyverse','bench'), dependencies=TRUE)"
RUN R -e "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/'));install.packages(c('BPCells', 'presto', 'glmGamPoi'))"

# Install Bioconductor packages
RUN R -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager'); BiocManager::install(c( 'scater', 'bluster'))"

# For GitHub packages, you can use remotes to install them. Example:
RUN R -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools'); devtools::install_github('GfellerLab/SuperCell')"
RUN R -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools'); devtools::install_github('GfellerLab/SuperSpot')"
RUN R -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools'); devtools::install_github('immunogenomics/presto')"

# For velocyto.R, which is not directly available via install.packages() or BiocManager::install()
# You might need to install it from GitHub or follow specific instructions provided by the package maintainers

RUN R -e "install.packages(c('peakRAM'), dependencies=TRUE)"

# Set default command to launch R
#CMD ["R"]
