---
title: "ARI Computations"
author: "Matei Teleman"
date: "2024-04-15"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(Seurat)
library(SeuratData)
library(dplyr)
library(tidyverse)
```


```{r}
metadata_151673 <- read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")
bayespace_results_spots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spot", pattern = "bayespace", full.names = TRUE)
cellcharter_results_spots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spot", pattern = "cellcharter", full.names = TRUE)
dr.sc_results_spots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spot", pattern = "dr_sc", full.names = TRUE)
graphST_results_spots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spot", pattern = "graphST", full.names = TRUE)
STAGATE_results_spots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spot", pattern = "STAGATE", full.names = TRUE)
```

## Compute mean ARI
```{r}
annotation_list <- c()
annotation_list$manual_annotation <- c("/Users/admin/Downloads/metadata.tsv")
annotation_list$graphst_clustering <- graphST_results_spots
annotation_list$stagate_clustering <- STAGATE_results_spots
annotation_list$cellcharter_clustering <- cellcharter_results_spots
annotation_list$dr.sc_clustering <- dr.sc_results_spots 
annotation_list$bayesspace_clustering <- bayespace_results_spots
```

```{r}
ari_matrix_mean <- matrix(nrow = 6, ncol = 6)
ari_matrix_max <- matrix(nrow = 6, ncol = 6)
for (i in 1:6){
  for (j in 1:6){
    print(i)
    print(j)
    aris <- c()
    for (m in 1:length(annotation_list[[i]])){
      for (n in 1:length(annotation_list[[j]])){
        if (grepl("bayespace|dr.sc",annotation_list[[i]][1])){
          clusts_1 <- na.omit(readxl::read_xlsx(annotation_list[[i]][m]) %>% column_to_rownames("cell"))
        }
        if (grepl("metadata",annotation_list[[i]][1])){
          clusts_1 <- read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")
          clusts_1 <- na.omit(clusts_1[,c("layer_guess"),drop = F])
        }
        if (grepl("STAGATE|cellcharter|graphST",annotation_list[[i]][1])){
           clusts_1 <- na.omit(readxl::read_xlsx(annotation_list[[i]][m]) %>% column_to_rownames("...1"))
        }
        if (grepl("bayespace|dr.sc",annotation_list[[j]][1])){
          clusts_2 <- na.omit(readxl::read_xlsx(annotation_list[[j]][n]) %>% column_to_rownames("cell"))
        }
        if (grepl("metadata",annotation_list[[j]][1])){
          clusts_2 <- read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")
          clusts_2 <- na.omit(clusts_2[,c("layer_guess"),drop = F])
        }
        if (grepl("STAGATE|cellcharter|graphST",annotation_list[[j]][1])){
           clusts_2 <- na.omit(readxl::read_xlsx(annotation_list[[j]][n]) %>% column_to_rownames("...1"))
        }
        common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
        new_clusts_1 <- clusts_1[common_cells,]
        new_clusts_2 <- clusts_2[common_cells,]
        ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
        aris <- c(aris,ari_tmp)
      }
    }
    ari_matrix_mean[i,j] <- mean(aris)
    ari_matrix_max[i,j] <- max(aris)
  }}    
    
```

```{r}
ari_matrix_mean
ari_matrix_max
```


```{r}
bayespace_results_metaspots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot", pattern = "bayespace", full.names = TRUE)
cellcharter_results_metaspots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot", pattern = "cellcharter", full.names = TRUE)
dr.sc_results_metaspots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot", pattern = "DRSC", full.names = TRUE)
graphST_results_metaspots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot", pattern = "graphST", full.names = TRUE)
STAGATE_results_metaspots <- list.files(path = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot", pattern = "STAGATE", full.names = TRUE)
```

```{r}
dlpfc151673 <- readRDS("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/cortex_with_membership.rds")
metaspots_positions <- read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_positions.csv")
```

```{r}
med_tmp <- dlpfc151673@meta.data
med_tmp$cell.id <- med_tmp %>% rownames()
bayespace_mapping_df <- data.frame(matrix(ncol = 0, nrow = 3639))

for (cl in bayespace_results_metaspots){
  bayesspace_clustering_metaspot <- readxl::read_xlsx(cl)
  bayesspace_clustering_metaspot$MC_membership_splv2 <- 1:nrow(bayesspace_clustering_metaspot)
  mapping_ms_bayesspace <- merge(bayesspace_clustering_metaspot[,c("spatial.cluster","MC_membership_splv2")],med_tmp[,c("cell.id" ,"MC_membership_splv2")])
  mapping_ms_bayesspace <- mapping_ms_bayesspace[match(rownames(dlpfc151673@meta.data),mapping_ms_bayesspace$cell.id),]
  bayespace_mapping_df <- cbind(bayespace_mapping_df,mapping_ms_bayesspace$spatial.cluster)
  dlpfc151673@meta.data$BayesSpace_clustering <- mapping_ms_bayesspace$spatial.cluster
  plot(SpatialDimPlot(dlpfc151673, group.by = "BayesSpace_clustering"))
}
rownames(bayespace_mapping_df) <- rownames(dlpfc151673@meta.data)

###
###

cellcharter_mapping_df <- data.frame(matrix(ncol = 0, nrow = 3639))

for (cl in cellcharter_results_metaspots){
  cellcharter_clustering_metaspot <- readxl::read_xlsx(cl)
  cellcharter_clustering_metaspot$MC_membership_splv2 <- 1:nrow(cellcharter_clustering_metaspot)
  mapping_ms_cellcharter <- merge(cellcharter_clustering_metaspot[,c("cluster_cellcharter","MC_membership_splv2")],med_tmp[,c("cell.id" ,"MC_membership_splv2")])
  mapping_ms_cellcharter <- mapping_ms_cellcharter[match(rownames(dlpfc151673@meta.data),mapping_ms_cellcharter$cell.id),]
  cellcharter_mapping_df <- cbind(cellcharter_mapping_df,mapping_ms_cellcharter$cluster_cellcharter)
  dlpfc151673@meta.data$CellCharter_clustering <- mapping_ms_cellcharter$cluster_cellcharter
  plot(SpatialDimPlot(dlpfc151673, group.by = "CellCharter_clustering"))
}
rownames(cellcharter_mapping_df) <- rownames(dlpfc151673@meta.data)


###
###

dr.sc_mapping_df <- data.frame(matrix(ncol = 0, nrow = 3639))

for (cl in dr.sc_results_metaspots){
  dr.sc_clustering_metaspot <- readxl::read_xlsx(cl)
  dr.sc_clustering_metaspot$MC_membership_splv2 <- 1:nrow(dr.sc_clustering_metaspot)
  mapping_ms_dr.sc <- merge(dr.sc_clustering_metaspot[,c("dr.sc_clustering","MC_membership_splv2")],med_tmp[,c("cell.id" ,"MC_membership_splv2")])
  mapping_ms_dr.sc <- mapping_ms_dr.sc[match(rownames(dlpfc151673@meta.data),mapping_ms_dr.sc$cell.id),]
  dr.sc_mapping_df <- cbind(dr.sc_mapping_df,mapping_ms_dr.sc$dr.sc_clustering)
  dlpfc151673@meta.data$dr.sc_clustering <- mapping_ms_dr.sc$dr.sc_clustering
  plot(SpatialDimPlot(dlpfc151673, group.by = "dr.sc_clustering"))
}
rownames(dr.sc_mapping_df) <- rownames(dlpfc151673@meta.data)


###
###

graphst_mapping_df <- data.frame(matrix(ncol = 0, nrow = 3639))

for (cl in graphST_results_metaspots){
  graphst_clustering_metaspot <- readxl::read_xlsx(cl)
  graphst_clustering_metaspot$MC_membership_splv2 <- 1:nrow(graphst_clustering_metaspot)
  mapping_ms_graphst <- merge(graphst_clustering_metaspot[,c("mclust","MC_membership_splv2")],med_tmp[,c("cell.id" ,"MC_membership_splv2")])
  mapping_ms_graphst <- mapping_ms_graphst[match(rownames(dlpfc151673@meta.data),mapping_ms_graphst$cell.id),]
  graphst_mapping_df <- cbind(graphst_mapping_df,mapping_ms_graphst$mclust)
  dlpfc151673@meta.data$graphst_clustering <- mapping_ms_graphst$mclust
  plot(SpatialDimPlot(dlpfc151673, group.by = "graphst_clustering"))
}
rownames(graphst_mapping_df) <- rownames(dlpfc151673@meta.data)

###
###
STAGATE_mapping_df <- data.frame(matrix(ncol = 0, nrow = 3639))

for (cl in STAGATE_results_metaspots){
  print(cl)
  STAGATE_clustering_metaspot <- readxl::read_xlsx(cl)
  STAGATE_clustering_metaspot$MC_membership_splv2 <- 1:nrow(STAGATE_clustering_metaspot)
  mapping_ms_STAGATE <- merge(STAGATE_clustering_metaspot[,c("mclust","MC_membership_splv2")],med_tmp[,c("cell.id" ,"MC_membership_splv2")])
  mapping_ms_STAGATE <- mapping_ms_STAGATE[match(rownames(dlpfc151673@meta.data),mapping_ms_STAGATE$cell.id),]
  STAGATE_mapping_df <- cbind(STAGATE_mapping_df,mapping_ms_STAGATE$mclust)
  dlpfc151673@meta.data$stagate_clustering <- mapping_ms_STAGATE$mclust
  plot(SpatialDimPlot(dlpfc151673, group.by = "stagate_clustering"))
}
rownames(STAGATE_mapping_df) <- rownames(dlpfc151673@meta.data)
```

```{r}
aris <- c()
for (c in 1:10){
  clusts_1 <- na.omit(bayespace_mapping_df[,c,drop = F])
  clusts_2 <- na.omit(read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")[,c("layer_guess"),drop = F])
  common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
  new_clusts_1 <- clusts_1[common_cells,]
  new_clusts_2 <- clusts_2[common_cells,]
  ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
  aris <- c(aris,ari_tmp)
}
bayespace_ari_mean <- mean(aris)
bayespace_ari_max <- max(aris)

aris <- c()
for (c1 in 1:10){
  for (c2 in 1:10){
    clusts_1 <- na.omit(bayespace_mapping_df[,c1,drop = F])
    clusts_2 <- na.omit(readxl::read_xlsx(bayespace_results_spots[c2]) %>% column_to_rownames("cell"))
    common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
    new_clusts_1 <- clusts_1[common_cells,]
    new_clusts_2 <- clusts_2[common_cells,]
    ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
    aris <- c(aris,ari_tmp)
  }
}
bayespace_ari_mean_ms_vs_s <- mean(aris)
bayespace_ari_max_ms_vs_s <- max(aris)
```

```{r}
aris <- c()
for (c in 1:10){
  clusts_1 <- na.omit(cellcharter_mapping_df[,c,drop = F])
  clusts_2 <- na.omit(read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")[,c("layer_guess"),drop = F])
  common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
  new_clusts_1 <- clusts_1[common_cells,]
  new_clusts_2 <- clusts_2[common_cells,]
  ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
  aris <- c(aris,ari_tmp)
}
cellcharter_ari_mean <- mean(aris)
cellcharter_ari_max <- max(aris)

aris <- c()
for (c1 in 1:10){
  for (c2 in 1:10){
    clusts_1 <- na.omit(cellcharter_mapping_df[,c1,drop = F])
    clusts_2 <- na.omit(readxl::read_xlsx(cellcharter_results_spots[c2]) %>% column_to_rownames("...1"))
    common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
    new_clusts_1 <- clusts_1[common_cells,]
    new_clusts_2 <- clusts_2[common_cells,]
    ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
    aris <- c(aris,ari_tmp)
  }
}
cellcharter_ari_mean_ms_vs_s <- mean(aris)
cellcharter_ari_max_ms_vs_s <- max(aris)
```

```{r}
aris <- c()
for (c in 1:10){
  clusts_1 <- na.omit(dr.sc_mapping_df[,c,drop = F])
  clusts_2 <- na.omit(read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")[,c("layer_guess"),drop = F])
  common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
  new_clusts_1 <- clusts_1[common_cells,]
  new_clusts_2 <- clusts_2[common_cells,]
  ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
  aris <- c(aris,ari_tmp)
}
dr.sc_ari_mean <- mean(aris)
dr.sc_ari_max <- max(aris)

aris <- c()
for (c1 in 1:10){
  for (c2 in 1:10){
    clusts_1 <- na.omit(dr.sc_mapping_df[,c1,drop = F])
    clusts_2 <- na.omit(readxl::read_xlsx(dr.sc_results_spots[c2]) %>% column_to_rownames("cell"))
    common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
    new_clusts_1 <- clusts_1[common_cells,]
    new_clusts_2 <- clusts_2[common_cells,]
    ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
    aris <- c(aris,ari_tmp)
  }
}
dr.sc_ari_mean_ms_vs_s <- mean(aris)
dr.sc_ari_max_ms_vs_s <- max(aris)
```

```{r}
aris <- c()
for (c in 1:10){
  clusts_1 <- na.omit(graphst_mapping_df[,c,drop = F])
  clusts_2 <- na.omit(read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")[,c("layer_guess"),drop = F])
  common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
  new_clusts_1 <- clusts_1[common_cells,]
  new_clusts_2 <- clusts_2[common_cells,]
  ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
  aris <- c(aris,ari_tmp)
}
graphst_ari_mean <- mean(aris)
graphst_ari_max <- max(aris)

aris <- c()
for (c1 in 1:10){
  for (c2 in 1:10){
    clusts_1 <- na.omit(graphst_mapping_df[,c1,drop = F])
    clusts_2 <- na.omit(readxl::read_xlsx(graphST_results_spots[c2]) %>% column_to_rownames("...1"))
    common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
    new_clusts_1 <- clusts_1[common_cells,]
    new_clusts_2 <- clusts_2[common_cells,]
    ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
    aris <- c(aris,ari_tmp)
  }
}
graphst_ari_mean_ms_vs_s <- mean(aris)
graphst_ari_max_ms_vs_s <- max(aris)
```

```{r}
aris <- c()
for (c in 1:10){
  clusts_1 <- na.omit(STAGATE_mapping_df[,c,drop = F])
  clusts_2 <- na.omit(read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")[,c("layer_guess"),drop = F])
  common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
  new_clusts_1 <- clusts_1[common_cells,]
  new_clusts_2 <- clusts_2[common_cells,]
  ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
  aris <- c(aris,ari_tmp)
}
STAGATE_ari_mean <- mean(aris)
STAGATE_ari_max <- max(aris)

aris <- c()
for (c1 in 1:10){
  for (c2 in 1:10){
    clusts_1 <- na.omit(STAGATE_mapping_df[,c1,drop = F])
    clusts_2 <- na.omit(readxl::read_xlsx(STAGATE_results_spots[c2]) %>% column_to_rownames("...1"))
    common_cells <- intersect(rownames(clusts_1),rownames(clusts_2)) %>% sort()
    new_clusts_1 <- clusts_1[common_cells,]
    new_clusts_2 <- clusts_2[common_cells,]
    ari_tmp <- aricode::ARI(new_clusts_1,new_clusts_2)
    aris <- c(aris,ari_tmp)
  }
}
STAGATE_ari_mean_ms_vs_s <- mean(aris)
STAGATE_ari_max_ms_vs_s <- max(aris)
```

##

```{r}
bplot1 <- tibble(ARI = c(ari_matrix_mean[1,2],graphst_ari_mean,
                         ari_matrix_mean[1,3],STAGATE_ari_mean,
                         ari_matrix_mean[1,4],cellcharter_ari_mean,
                         ari_matrix_mean[1,5],dr.sc_ari_mean,
                         ari_matrix_mean[1,6],bayespace_ari_mean),
                 Algorithm = c(rep("GraphST",2),rep("STAGATE",2),rep("CellCharter",2),rep("DR.SC",2),rep("BayesSpace",2)), Condition = c("spot", "metaspot","spot", "metaspot", "spot", "metaspot", "spot", "metaspot", "spot", "metaspot"))
bplot1_v2 <- bplot1 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot")))
ggplot(bplot1_v2, aes(x = Algorithm, y = ARI, fill = Condition, colour = Condition))+geom_bar(stat = "identity", position = "dodge")+theme_bw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),text = element_text(size = 20),legend.position="top")+RotatedAxis()


bplot3 <- tibble(ARI = c(graphst_ari_mean_ms_vs_s,ari_matrix_mean[2,c(3:6)],
                         STAGATE_ari_mean_ms_vs_s,ari_matrix_mean[3,c(2,4:6)],
                         cellcharter_ari_mean_ms_vs_s,ari_matrix_mean[4,c(2,3,5,6)],
                         dr.sc_ari_mean_ms_vs_s,ari_matrix_mean[5,c(2:4,6)],
                         bayespace_ari_mean_ms_vs_s,ari_matrix_mean[6,c(2:5)]), 
                 Algorithm = c(rep("GraphST",5),
                               rep("STAGATE",5),
                               rep("CellCharter",5),
                               rep("DR.SC",5),
                               rep("BayesSpace",5)),
                 Condition = rep(c("metaspot",rep("spot",4)),5),
                 Against = c("GraphST","STAGATE","CellCharter","DR.SC","BayesSpace",
                             "STAGATE","GraphST","CellCharter","DR.SC","BayesSpace",
                             "CellCharter","GraphST","STAGATE","DR.SC","BayesSpace",
                             "DR.SC","GraphST","STAGATE","CellCharter","BayesSpace",
                             "BayesSpace","GraphST","STAGATE","CellCharter","DR.SC"))
ggplot(bplot3 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot"))), aes(x = Algorithm, y = ARI,))+
  geom_boxplot(data = subset(bplot3, Condition == "spot"),mapping = aes(x = Algorithm, y = ARI,))+
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, aes( fill = Condition),
               #position=position_dodge(0.1)
               ) +
  scale_fill_manual(values = c("metaspot" = "#00BFC4", "spot" = "black")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(size = 20),legend.position="top") +
  RotatedAxis()


ggplot() +
    geom_boxplot(data = subset(bplot3, Condition == "spot"), aes(x = Algorithm, y = ARI),outlier.size=0) +
    geom_point(data = bplot3 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot"))),position = position_jitterdodge(jitter.width = 0, dodge.width = 0), size = 5,mapping = aes(x = Algorithm, y = ARI,shape = Against, color = Condition))+
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          text = element_text(size = 20),
          legend.position = "top")+
    RotatedAxis()
```

```{r}
bplot1 <- tibble(ARI = c(ari_matrix_max[1,2],graphst_ari_max,
                         ari_matrix_max[1,3],STAGATE_ari_max,
                         ari_matrix_max[1,4],cellcharter_ari_max,
                         ari_matrix_max[1,5],dr.sc_ari_max,
                         ari_matrix_max[1,6],bayespace_ari_max),
                 Algorithm = c(rep("GraphST",2),rep("STAGATE",2),rep("CellCharter",2),rep("DR.SC",2),rep("BayesSpace",2)), Condition = c("spot", "metaspot","spot", "metaspot", "spot", "metaspot", "spot", "metaspot", "spot", "metaspot"))
bplot1_v2 <- bplot1 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot")))
ggplot(bplot1_v2, aes(x = Algorithm, y = ARI, fill = Condition, colour = Condition))+geom_bar(stat = "identity", position = "dodge")+theme_bw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),text = element_text(size = 20),legend.position="top")+RotatedAxis()


bplot3 <- tibble(ARI = c(graphst_ari_max_ms_vs_s,ari_matrix_max[2,c(3:6)],
                         STAGATE_ari_max_ms_vs_s,ari_matrix_max[3,c(2,4:6)],
                         cellcharter_ari_max_ms_vs_s,ari_matrix_max[4,c(2,3,5,6)],
                         dr.sc_ari_max_ms_vs_s,ari_matrix_max[5,c(2:4,6)],
                         bayespace_ari_max_ms_vs_s,ari_matrix_max[6,c(2:5)]), 
                 Algorithm = c(rep("GraphST",5),
                               rep("STAGATE",5),
                               rep("CellCharter",5),
                               rep("DR.SC",5),
                               rep("BayesSpace",5)),
                 Condition = rep(c("metaspot",rep("spot",4)),5),
                 Against = c("GraphST","STAGATE","CellCharter","DR.SC","BayesSpace",
                             "STAGATE","GraphST","CellCharter","DR.SC","BayesSpace",
                             "CellCharter","GraphST","STAGATE","DR.SC","BayesSpace",
                             "DR.SC","GraphST","STAGATE","CellCharter","BayesSpace",
                             "BayesSpace","GraphST","STAGATE","CellCharter","DR.SC"))
ggplot(bplot3 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot"))), aes(x = Algorithm, y = ARI,))+
  geom_boxplot(data = subset(bplot3, Condition == "spot"),mapping = aes(x = Algorithm, y = ARI,))+
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, aes( fill = Condition),
               #position=position_dodge(0.1)
               ) +
  scale_fill_manual(values = c("metaspot" = "#00BFC4", "spot" = "black")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(size = 20),legend.position="top") +
  RotatedAxis()


ggplot() +
    geom_boxplot(data = subset(bplot3, Condition == "spot"), aes(x = Algorithm, y = ARI),outlier.size=0) +
    geom_point(data = bplot3 %>% dplyr::mutate(Condition = factor(Condition, levels = c("spot","metaspot"))),position = position_jitterdodge(jitter.width = 0, dodge.width = 0), size = 5,mapping = aes(x = Algorithm, y = ARI,shape = Against, color = Condition))+
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          text = element_text(size = 20),
          legend.position = "top")+
    RotatedAxis()
```

