---
title: "Benchmarking Metaspots"
author: "Matei Teleman"
date: "2024-04-15"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Creating Metaspots
```{r}
library(igraph)
library(pbapply)
library(tidyr)
library(tidyverse)
library(igraph)
library(SuperCell)
library(SeuratObject)
library(Seurat)
library(patchwork)
library(ggplot2)
library(dplyr)
library(hdf5r)
library(scales)
library(ggpubr)
library(networkD3)
library(ggforce)
library(clusterProfiler)
library(SuperSpot)
dlpfc151673 <- Load10X_Spatial("/Users/admin/Downloads/151673")
dlpfc151673 <- readRDS("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/cortex_with_membership.rds")
metadata_151673 <- read.table("/Users/admin/Downloads/metadata.tsv",sep = "\t")
dlpfc151673@meta.data$layer_guess <- metadata_151673$layer_guess
dlpfc151673@meta.data$layer_guess[is.na(dlpfc151673@meta.data$layer_guess)] <- "Unknown"
dlpfc151673 <- RenameIdents(dlpfc151673, 'WM' = 'White Matter')
SpatialDimPlot(dlpfc151673,group.by = "layer_guess")

#mtx <- dlpfc151673@assays$Spatial@layers$counts# %>% as.data.frame()
mtx <- GetAssayData(dlpfc151673,assay = "Spatial",layer = "counts")

spotPositions <- GetTissueCoordinates(dlpfc151673)

dlpfc151673 <- FindVariableFeatures(dlpfc151673,nfeatures = 2000)
hvg <- VariableFeatures(dlpfc151673)

MC_DLS.spl <- SCimplify_SpatialDLS(X = mtx,
                                   spotPositions = spotPositions,
                                   method_similarity = "1",
                                   genes.use = hvg,gamma = 4,
                                   n.pc = 1:30,
                                   method_knn = "1",
                                   k.knn = 6 ,
                                   #cell.annotation = dlpfc151673@meta.data$layer_guess ,
                                   method_normalization = "log_normalize",split_not_connected = T)

dlpfc151673@meta.data$MC_membership_spl <- MC_DLS.spl$membership %>% as.character()

MC_DLS.spl$layer_guess <- supercell_assign(clusters = dlpfc151673@meta.data$layer_guess,supercell_membership = MC_DLS.spl$membership,method = "absolute")

method_purity <- c("max_proportion", "entropy")[1]
MC_DLS.spl$purity_annot <- supercell_purity(
  clusters = dlpfc151673@meta.data$layer_guess,
  supercell_membership = MC_DLS.spl$membership, 
  method = method_purity
)


MC_DLS.spl$MS_coord <- supercell_spatial_centroids(MC_DLS.spl,spotPositions)

MC_DLS.splv2 <- split_unconnected(MC_DLS.spl)
dlpfc151673@meta.data$MC_membership_splv2 <- MC_DLS.splv2$membership %>% as.character()

MC_DLS.splv2$layer_guess <- supercell_assign(clusters = dlpfc151673@meta.data$layer_guess,supercell_membership = MC_DLS.splv2$membership,method = "absolute")

MC_DLS.splv2$polygons <- supercell_metaspots_shape(MC = MC_DLS.splv2,spotpositions = spotPositions,annotation = "layer_guess",concavity = 2,membership_name = "membership")

SpatialDimPlotSC(original_coord = spotPositions,MC = MC_DLS.splv2,
                    sc.col = "layer_guess",sc.col2 = "MC_membership_splv2",polygons_col = "polygons" ,meta_data = dlpfc151673@meta.data, alpha_hull = 0.5)+
  theme(panel.background = element_rect(fill="black"),
        plot.background = element_rect(fill="black"),
        panel.grid = element_line(color="black"),
        axis.text = element_text(color="white"),
        axis.title = element_text(color="white"),
        legend.background = element_rect(fill="black"),
        legend.text = element_text(color="white"))+NoLegend()+coord_fixed()

SpatialDimPlotSC(original_coord = spotPositions,MC = MC_DLS.splv2,
                    sc.col = "layer_guess",sc.col2 = "MC_membership_splv2",polygons_col = "polygons" ,meta_data = dlpfc151673@meta.data, alpha_hull = 0.5)+
  theme(panel.background = element_rect(fill="white"),
        plot.background = element_rect(fill="white"),
        panel.grid = element_line(color="white"),
        axis.text = element_text(color="black"),
        axis.title = element_text(color="black"),
        legend.background = element_rect(fill="black"),
        legend.text = element_text(color="black"))+NoLegend()+coord_fixed()




MC_DLS.splv2$MS_coord <- supercell_spatial_centroids(MC_DLS.splv2,spotPositions)
```



```{r}
MC.spl.gev2 <- superspot_GE(MC = MC_DLS.splv2,
  ge = GetAssayData(dlpfc151673,assay = "Spatial",slot = "counts"),
  #ge = mtx,
  groups = MC_DLS.splv2$membership,mode = "sum"
)

MC.spl.seuratv2 <- supercell_2_Seuratv5(
  SC.GE = MC.spl.gev2, 
  SC = MC_DLS.splv2, 
  fields = c("layer_guess")
)

MC.spl.seuratv2 <- NormalizeData(MC.spl.seuratv2)

MC.spl.seuratv2 <- ScaleData(MC.spl.seuratv2)

MC.spl.seuratv2 <- FindVariableFeatures(MC.spl.seuratv2)

MC.spl.seuratv2 <- RunPCA(MC.spl.seuratv2)

MC.spl.seuratv2 <- RunUMAP(MC.spl.seuratv2, dims = 1:30)

DimPlot(MC.spl.seuratv2, reduction = "umap", group.by = "layer_guess")
```


```{r}
write.csv(x = t(GetAssayData(MC.spl.seuratv2,assay = "RNA",slot = "count") %>% as.matrix()),file = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_counts.csv")

rownames(MC_DLS.splv2$MS_coord) <- paste0("X",rownames(MC_DLS.splv2$MS_coord))

write.csv(x = MC_DLS.splv2$MS_coord[,c("imagerow","imagecol")],file = "/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_positions.csv",row.names = F)
```


```{r}
tissue_positions <- read.csv("/Users/admin/Downloads/151673/spatial/tissue_positions_list.csv",header = F)
tissue_positions_sb <- subset(tissue_positions, V1 %in% intersect(names(MC_DLS.splv2$membership),tissue_positions$V1))

identical(names(MC_DLS.splv2$membership),tissue_positions_sb$V1)

tissue_positions_sb <- tissue_positions_sb[match(names(MC_DLS.splv2$membership),tissue_positions_sb$V1),]

identical(names(MC_DLS.splv2$membership),tissue_positions_sb$V1)

tissue_positions_sb$membership <- MC_DLS.splv2$membership

rownames(tissue_positions_sb) <- NULL

tissue_positions_sb <- column_to_rownames(tissue_positions_sb,"V1")

metaspot_tissue_position <- stats::aggregate(tissue_positions_sb %>% as.matrix() ~membership,tissue_positions_sb,mean)

metaspot_tissue_position$membership <- paste0("X",metaspot_tissue_position$membership)
```

```{r}
write_csv(metaspot_tissue_position[,1:6],"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot_tissue_positions_list.csv",col_names = F)
```


## Clustering on Metaspots


```{r}
reticulate::use_miniconda("/Users/admin/miniconda3")

#reticulate::use_miniconda("/Users/admin/miniconda3/envs/cellcharter")
```


### Python Clustering methods
```{python}
import anndata as ad
import squidpy as sq
import pandas as pd
import scanpy as sc
import numpy as np
import matplotlib.pyplot as plt
import random
import os
import torch
from sklearn import metrics
import multiprocessing as mp
import GraphST
import sys

import STAGATE
```

#### GraphST

```{python}
seed_values = [random.randint(1, 10000) for _ in range(10)]
adata_metaspot = sc.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_counts.csv")
adata_metaspot.var_names_make_unique()

metaspot_position = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_positions.csv")

# Load the spatial coordinates
spatial_coords = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot_tissue_positions_list.csv", header=None, index_col=0)

# Assuming 'adata_metaspot' is your AnnData object with the count matrix
# Make sure that the index of spatial_coords matches the order of the barcodes in adata_metaspot.obs_names
#adata_metaspot.obsm['spatial'] = spatial_coords.loc[adata_metaspot.obs_names, [4, 5]].to_numpy()
adata_metaspot.obsm['spatial'] = spatial_coords.loc[:, [4, 5]].to_numpy()

# Add additional metadata_metaspot, if any, such as the image path
adata_metaspot.uns['spatial'] = {'images': '/Users/admin/Downloads/151673/spatial/tissue_lowres_image.png'}
```


```{python}
from GraphST import GraphST
# Run device, by default, the package is implemented on 'cpu'. We recommend using GPU.
device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')

# the location of R, which is necessary for mclust algorithm. Please replace the path below with local R installation path
os.environ['R_HOME'] = "/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources"
```

```{python}
for i in range (0,10):
  # the number of clusters
  n_clusters = 7
  dataset = '151673'
  # define model
  model = GraphST.GraphST(adata_metaspot, device=device,random_seed=seed_values[i])
  # train model
  adata_metaspot = model.train()
  # set radius to specify the number of neighbors considered during refinement
  radius = 50
  tool = 'mclust' # mclust, leiden, and louvain
  # clustering
  from GraphST.utils import clustering
  print(i)
  clustering(adata_metaspot, n_clusters, radius=radius, method=tool, refinement=True) # For DLPFC dataset, we use optional     refinement step.
  adata_metaspot.obs['mclust'].to_excel(f"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot/graphST_clustering_metaspot_{i}.xlsx")

#  sc.pl.spatial(adata_metaspot,
#              img_key="hires",
#              color=["domain"],
#              #title=["Ground truth", "ARI=%.4f"%ARI],
#              show=True)

  
```

#### STAGATE
```{python}
adata_metaspot = sc.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_counts.csv")
adata_metaspot.var_names_make_unique()

metaspot_position = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_positions.csv")

# Load the spatial coordinates
spatial_coords = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot_tissue_positions_list.csv", header=None, index_col=0)

# Assuming 'adata_metaspot' is your AnnData object with the count matrix
# Make sure that the index of spatial_coords matches the order of the barcodes in adata_metaspot.obs_names
#adata_metaspot.obsm['spatial'] = spatial_coords.loc[adata_metaspot.obs_names, [4, 5]].to_numpy()
adata_metaspot.obsm['spatial'] = spatial_coords.loc[:, [4, 5]].to_numpy()

# Add additional metadata_metaspot, if any, such as the image path
adata_metaspot.uns['spatial'] = {'images': '/Users/admin/Downloads/151673/spatial/tissue_lowres_image.png'}
```


```{python}
os.environ['R_HOME'] = "/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources"
os.environ['R_USER'] = '/Users/admin/miniconda3/lib/python3.10/site-packages/rpy2'
#adata_metaspot = sc.read_visium(path="/Users/admin/Downloads/151673", count_file='filtered_feature_bc_matrix.h5')
adata_metaspot.var_names_make_unique()
#Normalization
sc.pp.highly_variable_genes(adata_metaspot, flavor="seurat_v3", n_top_genes=3000)
sc.pp.normalize_total(adata_metaspot, target_sum=1e4,)
sc.pp.log1p(adata_metaspot,)
```

```{python}
import tensorflow.compat.v1 as tf
for i in range (0,10):
  tf.disable_eager_execution()

  STAGATE.Cal_Spatial_Net(adata_metaspot, rad_cutoff=400)
  STAGATE.Stats_Spatial_Net(adata_metaspot)

  adata_metaspot = STAGATE.train_STAGATE(adata_metaspot, alpha=0,random_seed=seed_values[i])


  sc.pp.neighbors(adata_metaspot, use_rep='STAGATE')
  sc.tl.umap(adata_metaspot)
  adata_metaspot = STAGATE.mclust_R(adata_metaspot, used_obsm='STAGATE', num_cluster=7)

  #sc.pl.spatial(adata_metaspot, color=["mclust"], title=['STAGATE'])

  adata_metaspot.obs['mclust'].to_excel(f"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot/STAGATE_clustering_metaspot_{i}.xlsx")

```

#### CellCharter

```{r}
reticulate::use_miniconda("/Users/admin/miniconda3/envs/cellcharter-env")
```


```{python}
import anndata as ad
import squidpy as sq
import cellcharter as cc
import pandas as pd
import scanpy as sc
import scvi
import numpy as np
import matplotlib.pyplot as plt
import random

seed_values = [random.randint(1, 10000) for _ in range(10)]
adata_metaspot = sc.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_counts.csv")
adata_metaspot.var_names_make_unique()

metaspot_position = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_positions.csv")

#adata_metaspot.obsm['spatial'] = metaspot_position


# Load the spatial coordinates
spatial_coords = pd.read_csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot_tissue_positions_list.csv", header=None, index_col=0)

# Assuming 'adata_metaspot' is your AnnData object with the count matrix
# Make sure that the index of spatial_coords matches the order of the barcodes in adata_metaspot.obs_names
#adata_metaspot.obsm['spatial'] = spatial_coords.loc[adata_metaspot.obs_names, [4, 5]].to_numpy()
adata_metaspot.obsm['spatial'] = spatial_coords.loc[:, [4, 5]].to_numpy()

# Flip y axis
#adata_metaspot.obsm['spatial_fov'][:, 1] = np.max(adata_metaspot.obsm['spatial_fov'][:, 1]) - adata_metaspot.obsm['spatial_fov'][:, 1]

# Remove negative probes
adata_metaspot = adata_metaspot[:, [c for c in adata_metaspot.var_names if 'NegPrb' not in c]].copy()
    
adata_metaspot.obs['sample'] = "151673"


```

```{python}

# 'spatial_fov' refers to global coordinates of the cells.
# Thus, we are going to use 'spatial_fov' and not 'spatial' as spatial coordinates.
#adata_metaspot.uns['spatial_fov'] = {s: {} for s in adata_metaspot.obs['sample'].unique()}
adata_metaspot.obs['sample'] = pd.Categorical(adata_metaspot.obs['sample'])
#adata_metaspot.uns['spatial'] = pd.Categorical(adata_metaspot.uns['spatial'])
adata_metaspot
```

```{python}
sc.pp.filter_genes(adata_metaspot, min_counts=3)
adata_metaspot
#sc.pp.filter_cells(adata_metaspot, min_counts=3)
#adata_metaspot
adata_metaspot.layers["counts"] = adata_metaspot.X.copy()

sc.pp.normalize_total(adata_metaspot, target_sum=1e6)
sc.pp.log1p(adata_metaspot)

adata_metaspot
```

```{python}
for i in range(0,10):
  scvi.settings.seed = seed_values[i]
  scvi.model.SCVI.setup_anndata(
    adata_metaspot, 
    layer="counts", 
    batch_key='sample')

  model = scvi.model.SCVI(adata_metaspot)
  model.train(early_stopping=True, enable_progress_bar=True)

  adata_metaspot.obsm['X_scVI'] = model.get_latent_representation(adata_metaspot).astype(np.float32)
  sq.gr.spatial_neighbors(adata_metaspot, library_key='sample', coord_type='generic', delaunay=True, spatial_key='spatial')
  cc.gr.remove_long_links(adata_metaspot)


  cc.gr.aggregate_neighbors(adata_metaspot, n_layers=3, use_rep='X_scVI', out_key='X_cellcharter', sample_key='sample')

  autok = cc.tl.ClusterAutoK(
      n_clusters=(2,10), 
      max_runs=10, 
      model_params=dict(
         random_state=seed_values[i]
        # If running on GPU
        #trainer_params=dict(accelerator='gpu', devices=1)
      )
  )

  autok.fit(adata_metaspot, use_rep='X_cellcharter')

  #plt.close()
  #cc.pl.autok_stability(autok)
  #plt.show()
  #plt.close()

  adata_metaspot.obs['cluster_cellcharter'] = autok.predict(adata_metaspot, use_rep='X_cellcharter',k=7)

  #sq.pl.spatial_scatter(
  #    adata_metaspot, 
  #    color=['cluster_cellcharter'], 
  #    library_key='sample',  
  #    size=1, 
  #    img=None,
  #    spatial_key='spatial',
  #    palette='Set2',
  #    #connectivity_key='spatial_connectivities',
  #    #img_alpha=0.3,
  #    figsize=(15,15),
  #    ncols=1,
  #    #library_id=adata_metaspot.obs['sample'].unique(),
  #    library_id=['151673'],
  #)

  #plt.show()
#plt.close()
  adata_metaspot.obs['cluster_cellcharter'].to_excel(f"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot/cellcharter_clustering_metaspot_{i}.xlsx")

```

### Cluster in R
```{r}
library("DR.SC")
library(Seurat)
library(SeuratData)
#library(BPCells)
library(dplyr)
library(tidyverse)
seed_values <- sample(1:10000, 10, replace = FALSE)

tissue_positions <- read.csv("/Users/admin/Downloads/151673/spatial/tissue_positions_list.csv",header = F)
tissue_positions_sb <- subset(tissue_positions, V1 %in% intersect(names(MC_DLS.splv2$membership),tissue_positions$V1))

identical(names(MC_DLS.splv2$membership),tissue_positions_sb$V1)

tissue_positions_sb <- tissue_positions_sb[match(names(MC_DLS.splv2$membership),tissue_positions_sb$V1),]

identical(names(MC_DLS.splv2$membership),tissue_positions_sb$V1)

tissue_positions_sb$membership <- MC_DLS.splv2$membership

rownames(tissue_positions_sb) <- NULL

tissue_positions_sb <- column_to_rownames(tissue_positions_sb,"V1")

metaspot_tissue_position <- stats::aggregate(tissue_positions_sb %>% as.matrix() ~membership,tissue_positions_sb,mean)

metaspot_tissue_position$membership <- paste0("Cell_",metaspot_tissue_position$membership)

write_csv(metaspot_tissue_position[,1:6],"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spatial/tissue_positions_list.csv",col_names = F)

count_mtx <- read.csv("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspots_counts.csv")

dlpfc151673_metaspot <- CreateSeuratObject(counts = t(count_mtx[,2:ncol(count_mtx)]),assay = "Spatial")

metaspot_image <- Read10X_Image("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/spatial")

dlpfc151673_metaspot@images$slice1 <- metaspot_image

SpatialDimPlot(dlpfc151673_metaspot)

count <- dlpfc151673_metaspot@assays$Spatial@layers$counts
#meta_data <- data.frame(row=dlpfc151673_metaspot@images[["slice1"]]@coordinates[["row"]], col=dlpfc151673_metaspot@images[["slice1"]]@coordinates[["col"]])
meta_data <- data.frame(row=GetTissueCoordinates(dlpfc151673_metaspot)$y, col=GetTissueCoordinates(dlpfc151673_metaspot)$x)
row.names(meta_data) <- colnames(count)
## create Seurat object
so <- CreateSeuratObject(counts=count, meta.data = meta_data)
head(so)

# standard log-normalization
so <- NormalizeData(so)
# choose 500 highly variable features
seu <- FindVariableFeatures(so, nfeatures = 500, verbose = T)

```

```{r}
for (i in 1:10){
  ### Given K
seu <- DR.SC(seu, K=7, platform = 'Visium', verbose=F)
#Visualization

spatialPlotClusters(seu)
#Show the tSNE plot based on the extracted features from DR-SC.

drscPlot(seu)
#Show the UMAP plot based on the extracted features from DR-SC.

dlpfc151673_metaspot@meta.data$dr.sc_clustering <- seu$spatial.drsc.cluster
SpatialDimPlot(dlpfc151673_metaspot,group.by = "dr.sc_clustering")
writexl::write_xlsx(dlpfc151673_metaspot@meta.data[,"dr.sc_clustering",drop = F],paste0("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot/DRSC_clustering_metaspot_",i,".xlsx"))
}


```
```{r}
library(BayesSpace)
#dlpfc151673_metaspot <- NormalizeData(dlpfc151673_metaspot)

insh <- as.SingleCellExperiment(dlpfc151673_metaspot)
insh@colData@listData$row <- meta_data$row #dlpfc151673_metaspot@images[["slice1"]]@coordinates[["row"]]
insh@colData@listData$col <- meta_data$col #dlpfc151673_metaspot@images[["slice1"]]@coordinates[["col"]]
insh@colData@listData$imagerow <- meta_data$row #dlpfc151673_metaspot@images[["slice1"]]@coordinates[["imagerow"]]
insh@colData@listData$imagecol <- meta_data$col #dlpfc151673_metaspot@images[["slice1"]]@coordinates[["imagecol"]]

for (i in 1:10){
  set.seed(seed_values[i])
insh <- spatialPreprocess(insh, platform="Visium",n.PCs=7, n.HVGs=2000, log.normalize=T)
#insh <- qTune(insh, qs=seq(2, 50), platform="ST", d=7)
qPlot(insh)

set.seed(seed_values[i])
insh <- spatialCluster(insh, q=7, platform="Visium", d=7,init.method="mclust", model="t", gamma=3,nrep=1000, burn.in=100,save.chain=TRUE,)
head(colData(insh))

clusterPlot(insh)

clusterPlot(insh)


writexl::write_xlsx(x = as.data.frame(colData(insh)[,"spatial.cluster",drop = F]),path = paste0("/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/metaspot/bayespace_clustering_metaspot_",i,".xlsx"))
}

```
```{r}
saveRDS(dlpfc151673,"/Users/admin/Documents/These/Output/SC_DLS/Benchmarking_Mouse_Cortex_v2/cortex_with_membership.rds")
```

